spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurante
    username: postgres
    password: test1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "hellothisismrpresidenttrumpimheretodaytotelyouaboutsquarespace"  # reemplaza por una clave segura en prod
  access-token-expiration-ms: 900000            # 15 minutos = 900_000 ms
  refresh-token-expiration-ms: 604800000