spring:
  application:
    name: pnc-parcial-final-restaurante

  profiles:
    active: dev

jwt:
  secret: "CHANGEME_very_long_random_secret_key_for_dev"
  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 604800000

---
# Perfil: docker (Postgres)
spring:
  config:
    activate:
      on-profile: docker
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: "${JWT_SECRET:CHANGEME_very_long_random_secret_key_for_docker}"
  access-token-expiration-ms: "${JWT_ACCESS_TOKEN_EXPIRATION_MS:900000}"
  refresh-token-expiration-ms: "${JWT_REFRESH_TOKEN_EXPIRATION_MS:604800000}"